export const teams = [
  {
    id: 1,
    name: 'T1',
    logo: '/images/t1.png',
    lckWins: 10,
    worldsWins: 6,
    founded: 2003,
    sponsor: 'SK',
    roster: ['Doran', 'Oner', 'Faker', 'Peyz', 'Keria'],
    instagram: 'https://www.instagram.com/t1lol',
    youtube: 'https://www.youtube.com/@T1',
  },
  {
    id: 2,
    name: 'Gen.G',
    logo: '/images/geng.png',
    lckWins: 7,
    worldsWins: 2,
    founded: 2017,
    sponsor: 'KSV',
    roster: ['Kiin', 'Canyon', 'Chovy', 'Ruler', 'Duro'],
    instagram: 'https://www.instagram.com/gengesports',
    youtube: 'https://www.youtube.com/GenGesports',
  },
  {
    id: 3,
    name: 'DK',
    logo: '/images/dk.png',
    lckWins: 3,
    worldsWins: 1,
    founded: 2017,
    sponsor: 'ABYSS COMPANY',
    roster: ['Siwoo', 'Lucid', 'ShowMaker', 'Smash', 'Career'],
    instagram: 'https://www.instagram.com/dpluskia.lol/?hl=ko',
    youtube: 'https://www.youtube.com/@DplusKIA_LOL',
  },
  {
    id: 4,
    name: 'HLE',
    logo: '/images/hle.png',
    lckWins: 3,
    worldsWins: 0,
    founded: 2016,
    sponsor: 'Hanwha Life',
    roster: ['Zeus', 'Kanavi', 'Zeka', 'Gumayusi', 'Delight'],
    instagram: 'https://www.instagram.com/hle.official/',
    youtube: 'https://www.youtube.com/hanwhalifeesports',
  },
  {
    id: 5,
    name: 'KT',
    logo: '/images/kt.png',
    lckWins: 2,
    worldsWins: 0,
    founded: 2013,
    sponsor: 'KT Sports',
    roster: ['PerfecT', 'Cuzz', 'Bdd', 'Aiming', 'Effort'],
    instagram: 'https://www.instagram.com/ktrolstagram/?hl=ko',
    youtube: 'https://www.youtube.com/c/ktRolster_VOD',
  },
  {
    id: 6,
    name: 'DNS',
    logo: '/images/dns.png',
    lckWins: 0,
    worldsWins: 0,
    founded: 2019,
    sponsor: 'SOOP',
    roster: ['DuDu', 'Pyosik', 'Clozer', 'deokdam', 'Peter'],
    instagram: 'https://www.instagram.com/soopers_lol/',
    youtube: 'https://www.youtube.com/@SOOPers_LoL',
  },
  {
    id: 7,
    name: 'BNK',
    logo: '/images/bnk.png',
    lckWins: 0,
    worldsWins: 0,
    founded: 2020,
    sponsor: '4by4',
    roster: ['Clear', 'Raptor', 'VicLa', 'Taeyoon', 'Kellin'],
    instagram: 'https://www.instagram.com/bnk_fearx/',
    youtube: 'https://www.youtube.com/channel/UCxedTJNaGRHiq6YfNtQVCNA/videos',
  },
  {
    id: 8,
    name: 'DRX',
    logo: '/images/drx.png',
    lckWins: 2,
    worldsWins: 1,
    founded: 2015,
    sponsor: 'DRX',
    roster: ['Rich', 'Vincenzo', 'Ucal', 'Jiwoo', 'Andil'],
    instagram: 'https://www.instagram.com/drxglobal/?hl=ko',
    youtube: 'https://www.youtube.com/@DRXGlobal',
  },
  {
    id: 9,
    name: 'NS',
    logo: '/images/ns.png',
    lckWins: 0,
    worldsWins: 0,
    founded: 2018,
    sponsor: 'NS Esports',
    roster: ['Kingen', 'Sponge', 'Scout', 'Diable', 'Lehends'],
    instagram: 'https://www.instagram.com/ns_redforce/',
    youtube: 'https://www.youtube.com/@NSRedForce',
  },
  {
    id: 10,
    name: 'BRO',
    logo: '/images/bro.png',
    lckWins: 1,
    worldsWins: 0,
    founded: 2019,
    sponsor: 'BRION Esports',
    roster: ['Casting', 'GIDEON', 'Roamer', 'Teddy', 'Namgung'],
    instagram: 'https://www.instagram.com/brionesports/',
    youtube: 'https://www.youtube.com/@BRIONESPORTS',
  },
];